export enum EventType {
    ACCOUNT_STATUS_CHANGED,
    CLIENT_AGREED,
    CREATED,
    DOCUMENT_CHANGED,
    EMAIL_CONFIRMED,
    EMAIL_SENT,
    FIELD_CHANGED,
    NOT_INTERESTED,
    PERSONAL_DETAILS_UPDATE,
    REGISTRATION_STATE_CHANGED
}